module.exports = {
  'name': '姓名',
  'en_name': '英文姓名',
  'position': '职位',
  'en_position': '英文职位',
  'department': '部门',
  'en_department': '英文部门',
  'company': '公司',
  'en_company': '英文公司',
  'address': '地址',
  'en_address': '英文地址',
  'postcode': '邮编',
  'email': '邮箱',
  'website': '网址',
  'mobile': '手机',
  'phone': '电话',
  'fax': '传真',
  'qq': 'QQ',
  'msn': 'MSN',
  'wechat': '微信',
  'weibo': '微博',
  'company_id': '公司账号',
  'logo': 'logo',
  'others': '其他'
};