module.exports = {
  '姓名': 'name',
  '英文姓名': 'en_name',
  '职位': 'position',
  '英文职位': 'en_position',
  '部门': 'department',
  '英文部门': 'en_department',
  '公司': 'company',
  '英文公司': 'en_company',
  '地址': 'address',
  '英文地址': 'en_address',
  '邮编': 'postcode',
  '邮箱': 'email',
  '网址': 'website',
  '手机': 'mobile',
  '电话': 'phone',
  '传真': 'fax',
  'QQ': 'qq',
  'MSN': 'msn',
  '微信': 'wechat',
  '微博': 'weibo',
  '公司账号': 'company_id',
  'logo': 'logo',
  '其他': 'others'
};